name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: 3.22.185.104
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/NestJs-HW
            npm install
            npm run build
            pm2 restart 0
            exit          